services:
  app:
    build: .
    container_name: castellon-comercios-api
    restart: always
    env_file: .env
    ports:
      - "12001:12001"
    depends_on:
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm start
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: castellon-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - internal
    expose:
      - "6379" # solo visible dentro del stack

volumes:
  redis_data:

networks:
  internal:
    driver: bridge
